name: ci

on:
  push:
    branches:
      - "**"

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  GITHUB_SHA: ${{ github.sha }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  lint:
    name: lint
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run lint
        run: make lint

  test:
    name: test
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit test
        run: make test

