name: release

on:
  push:
    branches:
      - "release-v*"

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  GITHUB_SHA: ${{ github.sha }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build-docker-image:
    name: docker-build
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build
        run: make build-docker
  deploy-new-image:
    name: docker-deploy
    runs-on: self-hosted
    needs: build-docker-image
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run deploy
        run: make deploy-new-image


